Anonymization of exam sheets
cvlab-ai/splinter pull request #107
Opened 2024-05-06 17:32 UTC by Madek1

2024-06-05 21:34 UTC, Krystian030 requested changes
I've made a few additions to the script. Please note that the script doesn't work propery for data from https://luz6.eti.pg.gda.pl:7778/s/O9X4WgtB8KkV8WE. Additionally, I encountered some initial difficulties running the script, hence the additions. Regarding memory usage, it's currently within reasonable limits (<10 GB), so the optimization is not required.

2024-06-05 21:34 UTC, Krystian030 commented on research/exam-sheets-anonymization/main.py
I suggest using if __name__ == "__main__": to wrap the script's main execution code.

2024-06-05 21:34 UTC, Krystian030 commented on research/exam-sheets-anonymization/main.py
Also I recommend adding logging or print statements to the script to provide information on how many files have been processed and how many remain

2024-06-05 21:34 UTC, Krystian030 commented on research/exam-sheets-anonymization/main.py
Add README file with instructions on how to use the script

2024-06-05 21:34 UTC, Krystian030 commented on research/exam-sheets-anonymization/main.py
> +import tqdm
Here are the unused imports

2024-06-05 21:34 UTC, Krystian030 commented on research/exam-sheets-anonymization/main.py
> +import tqdm
Also I don't see the imports for functions from utils.py

2024-06-05 21:34 UTC, Krystian030 commented on research/exam-sheets-anonymization/utils.py
> +  height, _, _ = img.shape
img variable doesn't exist

2024-06-05 21:34 UTC, Krystian030 commented on research/exam-sheets-anonymization/utils.py
Please use ctrl + alt + L to format the code and ctrl + alt + O to optimize imports before committing changes.

2024-06-05 21:34 UTC, Krystian030 commented on research/exam-sheets-anonymization/main.py
Please use ctrl + alt + L to format the code and ctrl + alt + O to optimize imports before committing changes.

2024-06-06 17:59 UTC, Madek1 commented on research/exam-sheets-anonymization/main.py
I can format the code, but JFYI these shortcuts only work in the JetBrains IDEs ;)

2024-06-06 17:59 UTC, Madek1 commented on research/exam-sheets-anonymization/utils.py
I can format the code, but JFYI these shortcuts only work in the JetBrains IDEs ;)

2024-06-06 17:59 UTC, Madek1 commented on research/exam-sheets-anonymization/main.py
There is also no default formatter specified for this project. So I think we should do this in a separate task

2024-06-06 17:59 UTC, Madek1 commented on research/exam-sheets-anonymization/utils.py
There is also no default formatter specified for this project. So I think we should do this in a separate task

2024-06-06 17:59 UTC, Madek1 commented on research/exam-sheets-anonymization/main.py
I can add a readme file and improve the log system (a simple system already exists, you can search for "print" in the code)

2024-06-06 21:18 UTC, Madek1 commented on research/exam-sheets-anonymization/main.py
Fixed

2024-06-07 19:22 UTC, Krystian030 approved these changes
Double checked, LGTM

2024-06-07 20:03 UTC, S-cichocka approved these changes

2024-10-09 17:18 UTC, Krystian030 approved these changes

2024-10-09 17:18 UTC, merged