Issue/65/fix inference engine for real exam case
cvlab-ai/splinter pull request #66
Opened 2022-12-09 15:48 UTC by marekhering

2022-12-09 16:15 UTC, Debskij approved these changes

2022-12-09 16:15 UTC, Debskij commented on inference_engine/src/preprocessing/rotation/rotation.py
> +               abs(first_delta[1] - second_delta[1]) <= max(threshold, min(first_delta[1], second_delta[1]) / 10)
[Non blocking] Lets maybe move those value to some config file

2022-12-09 16:15 UTC, Debskij commented on inference_engine/src/preprocessing/rotation/rotation.py
> +        if abs(w - h) < min((w, h)) / 5:
[Non blocking] Lets maybe move those value to some config file

2022-12-10 16:28 UTC, leckijakub commented
@marekhering  tested with some scanned exams. Empty exam ![answers_1](https://user-images.githubusercontent.com/69140329/206864904-5b6788be-b724-4f9d-abe3-92c43b004c18.jpg) is detected as student `110477` .
Moreover, in both filled and empty scans exam_key is detected as [1,1,1,1]
![answers_3](https://user-images.githubusercontent.com/69140329/206865004-7f6f87f1-ba3d-41a0-b25c-1aea234d2643.jpg)

2022-12-10 16:28 UTC, leckijakub requested changes

2022-12-10 16:28 UTC, leckijakub commented on inference_engine/src/controller.py
> -            elif pdf_type == PDFType.answer_keys:
@marekhering this breaks handling of both students answers and answers keys. This hunk should be restored

2022-12-10 16:31 UTC, leckijakub commented
@marekhering to generate templates I changed color of letters in boxes from `darkgray` do `lightgray` in https://github.com/cvlab-ai/splinter/blob/main/research/answer_sheet_generator/constructs.py#L35

2022-12-10 18:03 UTC, leckijakub approved these changes
@marekhering Thanks for the updates, now the exams are correctly detected. Approve

2022-12-10 18:03 UTC, merged